---
 - name: Open http port (firewalld)
   firewalld: port={{ web_server_port }}/tcp permanent=true state=enabled
   notify:
   - Firewalld reload
   when: firewall_type == "firewalld"

 - name: Open http port (ufw)
   ufw: rule=allow port={{ web_server_port }} proto=tcp
   when: firewall_type == "ufw"

 - name: Open http port (iptables)
   iptables: chain=INPUT destination_port={{ web_server_port }} protocol=tcp jump=ACCEPT
   when: firewall_type == "iptables"

